### ISSUE TITLE
JFlex um OnSong-RegEx Ausdrücke erweitern 

### ISSUE THREAD

**Issue by matthiaw** [GebetshausFreiburg/songbook.printer#1]
Hi Barbara,
Es wäre gut im JFlex-Code erst den Javacode zu hinterlegen der von mir manuell ersetzt wurde, damit man bei Erweiterungen der Parser-Regeln keinen Mehraufwand im Nachgang hat.
Gruß,
Matthias

**Comment by BarbaraSN** [comment]
Ok. Ich hab gerade versucht zu verstehen was das heißt, aber ich checke es nicht.
Muss ich da was auf der Command Shell machen, oder was auf Eclipse von einem Ort zum anderen kopieren, oder...?

**Comment by matthiaw** [comment]
Ne. Dazu musst du unter /jflex/SongParserLogic.jflex in den Zeilen 15-19 den Code System.out... ersetzen mit den Zeilen 595-624 aus org.openskies.songbook.printer.LexicalSongParser.

Das bedeutet einfach nur, dass bei Ergänzung der  RegEx-Logik der Source-Code nicht immer manuell mit Copy&Paste erstetzt werden muss. Kannst es ja mal versuchen. Ich bastle gerade an was anderem. Wenn es nicht klappt kann ich es mal kurz machen und es dir "senden".

**Comment by matthiaw** [comment]
Du kannst aber auch erst einmal mit https://regexr.com/ weiter an den regular expression feilen um neben chrod-pro auch noch onSong-Zeilen einzubinden. Aber -uhhh-, schau mal was ich gerade gefunden habe: 

http://beta.onsongapp.com/docs/interface/menubar/utilities-menu/settings/import-settings/internet-settings/

**Comment by matthiaw** [comment]
Habe es korrigiert. Nun wird https://github.com/GebetshausFreiburg/songbook.printer/blob/master/src/org/openskies/songbook/printer/LexicalSongParser.java direkt erzeugt aus https://github.com/GebetshausFreiburg/songbook.printer/blob/master/jflex/SongParserLogic.jflex wenn man in der Konsole unter /songbook.printer/jflex den PArser-generator ausführt mit 'ava -jar jflex-1.6.1.jar SongParserLogic.jflex'. 

Somit können wir uns nun auf RexEx für OnSong fokussieren.
